# ==========================================
# TalentFlow AI - CloudWatch Monitoring
# ==========================================


# ==========================================
# 1. EC2 CPU Alarm
# ==========================================

resource "aws_cloudwatch_metric_alarm" "ec2_cpu_high" {
  alarm_name        = "terraform-talentflow-ec2-cpu-high"
  alarm_description = "Monitors high CPU utilization on the TalentFlow AI EC2 server."

  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1

  metric_name = "CPUUtilization"
  namespace   = "AWS/EC2"

  period    = 300
  statistic = "Average"
  threshold = 70

  dimensions = {
    InstanceId = aws_instance.talentflow_web.id
  }

  tags = {
    Project     = var.project_name
    Environment = var.environment
    Owner       = "sekhar"
  }
}


# ==========================================
# 2. RDS CPU Alarm
# ==========================================

resource "aws_cloudwatch_metric_alarm" "rds_cpu_high" {
  alarm_name        = "terraform-talentflow-rds-cpu-high"
  alarm_description = "Monitors high CPU utilization on the TalentFlow AI RDS database."

  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1

  metric_name = "CPUUtilization"
  namespace   = "AWS/RDS"

  period    = 300
  statistic = "Average"
  threshold = 70

  dimensions = {
    DBInstanceIdentifier = aws_db_instance.talentflow.id
  }

  tags = {
    Project     = var.project_name
    Environment = var.environment
    Owner       = "sekhar"
  }
}


# ==========================================
# 3. Lambda Errors Alarm
# ==========================================

resource "aws_cloudwatch_metric_alarm" "lambda_errors" {
  alarm_name        = "terraform-talentflow-lambda-errors"
  alarm_description = "Monitors errors generated by the TalentFlow AI Lambda function."

  comparison_operator = "GreaterThanOrEqualToThreshold"
  evaluation_periods  = 1

  metric_name = "Errors"
  namespace   = "AWS/Lambda"

  period    = 300
  statistic = "Sum"
  threshold = 1

  dimensions = {
    FunctionName = aws_lambda_function.resume_processor.function_name
  }

  tags = {
    Project     = var.project_name
    Environment = var.environment
    Owner       = "sekhar"
  }
}